CREATE TABLE alembic_version (
	version_num VARCHAR(32) NOT NULL, 
	CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);
------------------------------
CREATE TABLE approval_order (
	level INTEGER NOT NULL, 
	designation auth_user.designationtype NOT NULL, 
	approval_type roletype NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	description TEXT, 
	CONSTRAINT approval_order_pkey PRIMARY KEY (level)
);
------------------------------
CREATE TABLE employee (
	serial_number INTEGER GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 CYCLE), 
	employee_id TEXT NOT NULL, 
	first_name VARCHAR NOT NULL, 
	last_name VARCHAR, 
	email VARCHAR NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT employee_pkey PRIMARY KEY (employee_id), 
	CONSTRAINT employee_email_key UNIQUE NULLS DISTINCT (email), 
	CONSTRAINT employee_serial_number_key UNIQUE NULLS DISTINCT (serial_number)
);
------------------------------
CREATE TABLE categories (
	category_id TEXT DEFAULT concat('CAT-', to_char(nextval('master.category_id_seq'::regclass), 'FM0000'::text)) NOT NULL, 
	category_code TEXT NOT NULL, 
	category_name TEXT NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	is_active BOOLEAN NOT NULL, 
	CONSTRAINT categories_pkey PRIMARY KEY (category_id)
);
------------------------------
CREATE TABLE location (
	location_id SERIAL NOT NULL, 
	location_name TEXT NOT NULL, 
	location_type TEXT NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	CONSTRAINT location_pkey PRIMARY KEY (location_id)
);
------------------------------
CREATE TABLE products (
	product_id TEXT DEFAULT concat('PROD-', to_char(nextval('master.product_id_seq'::regclass), 'FM0000'::text)) NOT NULL, 
	product_name TEXT NOT NULL, 
	product_name_description TEXT NOT NULL, 
	product_type producttype NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	teams auth_user.team[] DEFAULT '{}'::auth_user.team[] NOT NULL, 
	CONSTRAINT products_pkey PRIMARY KEY (product_id)
);
------------------------------
CREATE TABLE permissions (
	permission_id SERIAL NOT NULL, 
	level INTEGER NOT NULL, 
	request_type requesttype NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	CONSTRAINT permissions_pkey PRIMARY KEY (permission_id), 
	CONSTRAINT permissions_level_fkey FOREIGN KEY(level) REFERENCES auth_user.approval_order (level) ON DELETE SET NULL ON UPDATE CASCADE
);
------------------------------
CREATE TABLE parts (
	part_id TEXT DEFAULT concat('PT-', to_char(nextval('master.part_id_seq'::regclass), 'FM0000'::text)) NOT NULL, 
	part_number TEXT NOT NULL, 
	part_name TEXT NOT NULL, 
	category_id TEXT NOT NULL, 
	unit_price NUMERIC(10, 2) NOT NULL, 
	unit_of_measure VARCHAR NOT NULL, 
	asset_prefix VARCHAR NOT NULL, 
	is_asset_type BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE, 
	is_active BOOLEAN NOT NULL, 
	CONSTRAINT parts_pkey PRIMARY KEY (part_id), 
	CONSTRAINT parts_category_id_fkey FOREIGN KEY(category_id) REFERENCES master.categories (category_id) ON DELETE SET NULL ON UPDATE CASCADE, 
	CONSTRAINT parts_part_number_key UNIQUE NULLS DISTINCT (part_number)
);
------------------------------
CREATE TABLE users (
	serial_number INTEGER GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 START WITH 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 CYCLE), 
	employee_id TEXT NOT NULL, 
	role userrole NOT NULL, 
	password TEXT NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	level INTEGER, 
	blocked_at TIMESTAMP WITH TIME ZONE, 
	blocked_by TEXT, 
	block_reason TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	parent_employee_id TEXT, 
	permission_id INTEGER, 
	teams auth_user.team[] DEFAULT '{}'::auth_user.team[] NOT NULL, 
	CONSTRAINT users_pkey PRIMARY KEY (employee_id), 
	CONSTRAINT fk_parent_id FOREIGN KEY(parent_employee_id) REFERENCES auth_user.users (employee_id) ON DELETE SET NULL, 
	CONSTRAINT users_blocked_by_fkey FOREIGN KEY(blocked_by) REFERENCES auth_user.users (employee_id) ON DELETE SET NULL, 
	CONSTRAINT users_employee_id_fkey FOREIGN KEY(employee_id) REFERENCES auth_user.employee (employee_id) ON DELETE SET NULL, 
	CONSTRAINT users_level_fkey FOREIGN KEY(level) REFERENCES auth_user.approval_order (level) ON DELETE SET NULL, 
	CONSTRAINT users_permission_id_fkey FOREIGN KEY(permission_id) REFERENCES auth_user.permissions (permission_id) ON DELETE SET NULL, 
	CONSTRAINT users_employee_id_key UNIQUE NULLS DISTINCT (employee_id), 
	CONSTRAINT users_serial_number_key UNIQUE NULLS DISTINCT (serial_number)
);
------------------------------
CREATE TABLE login_history (
	id SERIAL NOT NULL, 
	user_id TEXT, 
	timestamp TIMESTAMP WITH TIME ZONE DEFAULT now(), 
	ip_address VARCHAR(45), 
	device_info VARCHAR, 
	status loginstatus NOT NULL, 
	CONSTRAINT login_history_pkey PRIMARY KEY (id), 
	CONSTRAINT login_history_user_id_fkey FOREIGN KEY(user_id) REFERENCES auth_user.users (employee_id) ON DELETE CASCADE
);
------------------------------
CREATE TABLE sale_orders (
	sale_order_id TEXT DEFAULT concat('SO-', to_char(nextval('so_id_seq'::regclass), 'SO0000'::text)) NOT NULL, 
	product_id TEXT NOT NULL, 
	customer_name TEXT NOT NULL, 
	customer_phone TEXT NOT NULL, 
	customer_email TEXT NOT NULL, 
	location_id INTEGER NOT NULL, 
	qty_ordered INTEGER NOT NULL, 
	unit_price NUMERIC(10, 2) NOT NULL, 
	total_price NUMERIC(10, 2) NOT NULL, 
	status statustype NOT NULL, 
	order_date TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	expected_delivery_date TIMESTAMP WITH TIME ZONE NOT NULL, 
	dispatched_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	dispatched_by TEXT NOT NULL, 
	remarks TEXT NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT sale_orders_pkey PRIMARY KEY (sale_order_id), 
	CONSTRAINT sale_orders_dispatched_by_fkey FOREIGN KEY(dispatched_by) REFERENCES auth_user.users (employee_id) ON DELETE SET NULL ON UPDATE CASCADE, 
	CONSTRAINT sale_orders_location_id_fkey FOREIGN KEY(location_id) REFERENCES master.location (location_id) ON DELETE SET NULL ON UPDATE CASCADE, 
	CONSTRAINT sale_orders_product_id_fkey FOREIGN KEY(product_id) REFERENCES master.products (product_id) ON DELETE SET NULL ON UPDATE CASCADE
);
------------------------------
CREATE TABLE sale_order_items (
	sale_order_item_id TEXT DEFAULT concat('SOI-', to_char(nextval('soi_id_seq'::regclass), 'SOI0000'::text)) NOT NULL, 
	sale_order_id TEXT NOT NULL, 
	product_id TEXT NOT NULL, 
	part_id TEXT NOT NULL, 
	qty INTEGER NOT NULL, 
	unit_price NUMERIC(10, 2) NOT NULL, 
	total NUMERIC(10, 2) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT sale_order_items_pkey PRIMARY KEY (sale_order_item_id), 
	CONSTRAINT sale_order_items_part_id_fkey FOREIGN KEY(part_id) REFERENCES master.parts (part_id) ON DELETE SET NULL ON UPDATE CASCADE, 
	CONSTRAINT sale_order_items_product_id_fkey FOREIGN KEY(product_id) REFERENCES master.products (product_id) ON DELETE SET NULL ON UPDATE CASCADE, 
	CONSTRAINT sale_order_items_sale_order_id_fkey FOREIGN KEY(sale_order_id) REFERENCES sale_orders (sale_order_id) ON DELETE SET NULL ON UPDATE CASCADE
);
------------------------------