from fastapi import HTTPException
from typing import Tuple
from sqlalchemy import MetaData, Table
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings as global_setting
from app.schemas.dynamic_crud_schema import ColumnDefinition

def _validate_identifier(name: str, label: str) -> None:
    if not global_setting.IDENTIFIER_PATTERN.fullmatch(name):
        raise HTTPException(status_code=400, detail=f"Invalid {label}: {name}")

##########  
# def _reflect_table(db: Session, table_name: str) -> Table:
#     _validate_identifier(table_name, "table name")
#     metadata = MetaData()
#     try:
#         return Table(table_name, metadata, autoload_with=db.bind)
#     except SQLAlchemyError as exc:
#         raise HTTPException(status_code=404, detail=f"Table not found: {table_name}") from exc


async def _reflect_table_async(db: AsyncSession, table_name: str) -> Table:
    _validate_identifier(table_name, "table name")
    metadata = MetaData()
    try:
        # async reflection
        async with db.bind.connect() as conn:
            await conn.run_sync(metadata.reflect, only=[table_name])
        
        if table_name not in metadata.tables:
            raise HTTPException(status_code=404, detail=f"Table not found: {table_name}")
        
        return metadata.tables[table_name]
    
    except HTTPException:
        raise
    except SQLAlchemyError as exc:
        raise HTTPException(status_code=404, detail=f"Table not found: {table_name}") from exc

def _build_column_sql(col: ColumnDefinition, dialect_name: str, *, allow_auto_increment: bool) -> Tuple[str, bool]:
    # Validate column type to prevent SQL injection
    base_type = col.col_type.split("(")[0].strip().upper()
    if base_type not in global_setting.ALLOWED_SQL_TYPES:
        raise HTTPException(status_code=400, detail=f"Disallowed column type: {col.col_type}")

    constraints = list(dict.fromkeys(col.constraints))
    if len(constraints) != len(col.constraints):
        raise HTTPException(status_code=400, detail=f"Duplicate constraints for column: {col.name}")

    has_primary_key = "PRIMARY KEY" in constraints

    if has_primary_key and col.nullable:
        raise HTTPException(status_code=400, detail=f"PRIMARY KEY column cannot be nullable: {col.name}")

    if col.auto_increment and not allow_auto_increment:
        raise HTTPException(status_code=400, detail="Auto increment is only allowed during table creation")

    if col.auto_increment:
        if "sqlite" in dialect_name:
            return f'"{col.name}" INTEGER PRIMARY KEY AUTOINCREMENT', True
        parts = [f'"{col.name}"', "INTEGER", "GENERATED BY DEFAULT AS IDENTITY"]
        if "UNIQUE" in constraints:
            parts.append("UNIQUE")
        if "NONE" in constraints:
            parts.append("NULL")
        return " ".join(parts), has_primary_key

    parts = [f'"{col.name}"', col.col_type]

    if not col.nullable:
        parts.append("NOT NULL")

    for cons in constraints:
        parts.append(cons)

    return " ".join(parts), has_primary_key
