"""create and update application_tables schema for user_db_source, chat, and llm_api_keys

Revision ID: 20260818_app_tables_update
Revises: 20260818_leader_reassign
Create Date: 2026-08-18 16:10:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260818_app_tables_update'
down_revision: Union[str, None] = '20260818_leader_reassign'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 0. Ensure schema application_tables exists
    op.execute("CREATE SCHEMA IF NOT EXISTS application_tables;")

    # 1. llm_api_keys table
    op.execute("""
    CREATE TABLE IF NOT EXISTS application_tables.llm_api_keys (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        key_name VARCHAR(100),
        api_key TEXT NOT NULL,
        provider_name VARCHAR(100) NOT NULL DEFAULT 'openai',
        organization_id VARCHAR(100),
        status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
        rate_limited_at TIMESTAMP WITH TIME ZONE,
        next_available_at TIMESTAMP WITH TIME ZONE,
        last_used_at TIMESTAMP WITH TIME ZONE,
        priority INT NOT NULL DEFAULT 1,
        fail_count INT NOT NULL DEFAULT 0,
        max_tokens_limit INT,
        monthly_quota INT
    );
    """)

    # 2. chat_session table
    op.execute("""
    CREATE TABLE IF NOT EXISTS application_tables.chat_session (
        session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id TEXT NOT NULL REFERENCES sales.leaders(emp_id) ON DELETE CASCADE,
        title VARCHAR(255),
        model_name VARCHAR(100),
        system_prompt TEXT,
        agent_metadata JSONB,
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
        is_active BOOLEAN NOT NULL DEFAULT TRUE
    );
    """)

    # 3. chat_message table
    op.execute("""
    CREATE TABLE IF NOT EXISTS application_tables.chat_message (
        message_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        session_id UUID NOT NULL REFERENCES application_tables.chat_session(session_id) ON DELETE CASCADE,
        user_id TEXT NOT NULL REFERENCES sales.leaders(emp_id) ON DELETE CASCADE,
        content JSONB,
        chat_metadata JSONB,
        status VARCHAR(50) NOT NULL DEFAULT 'NO_RESULTS',
        feedback_rating INT,
        feedback_text TEXT,
        prompt_tokens INT,
        completion_tokens INT,
        total_tokens INT,
        model_name VARCHAR(100),
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    """)

    # 4. query_execution table
    op.execute("""
    CREATE TABLE IF NOT EXISTS application_tables.query_execution (
        query_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        session_id UUID NOT NULL REFERENCES application_tables.chat_session(session_id) ON DELETE CASCADE,
        message_id UUID NOT NULL REFERENCES application_tables.chat_message(message_id) ON DELETE CASCADE,
        sql_query TEXT NOT NULL,
        row_count INT,
        column_names VARCHAR(255)[],
        execution_time_ms INT,
        result_type VARCHAR(50),
        result_cache_key VARCHAR(100),
        csv_file_path VARCHAR(500),
        agent_name VARCHAR(100),
        tokens_used INT,
        csv_expires_at TIMESTAMP WITH TIME ZONE,
        result_preview JSONB,
        error_message TEXT,
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
        completed_at TIMESTAMP WITH TIME ZONE
    );
    """)

    # 5. user_db_source table
    op.execute("""
    CREATE TABLE IF NOT EXISTS application_tables.user_db_source (
        _id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        display_name VARCHAR NOT NULL,
        user_id TEXT NOT NULL REFERENCES sales.leaders(emp_id) ON DELETE CASCADE,
        database_type VARCHAR NOT NULL,
        driver VARCHAR NOT NULL,
        db_scheme VARCHAR NOT NULL,
        host VARCHAR NOT NULL,
        port INT NOT NULL,
        user_name VARCHAR NOT NULL,
        password VARCHAR NOT NULL,
        db_name VARCHAR NOT NULL,
        ssl_enabled BOOLEAN NOT NULL DEFAULT FALSE,
        ssl_mode VARCHAR(50),
        environment VARCHAR(50) DEFAULT 'development',
        connection_timeout INT DEFAULT 30,
        extra_params JSONB,
        is_active BOOLEAN NOT NULL DEFAULT FALSE,
        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT user_db_source_pk UNIQUE (display_name, user_id)
    );
    """)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS application_tables.user_db_source CASCADE;")
    op.execute("DROP TABLE IF EXISTS application_tables.query_execution CASCADE;")
    op.execute("DROP TABLE IF EXISTS application_tables.chat_message CASCADE;")
    op.execute("DROP TABLE IF EXISTS application_tables.chat_session CASCADE;")
    op.execute("DROP TABLE IF EXISTS application_tables.llm_api_keys CASCADE;")
