"""init_sales_schema

Revision ID: 20260806_init_sales_schema
Revises: 
Create Date: 2026-08-06 14:37:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260806_init_sales_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure schemas exist
    op.execute("CREATE SCHEMA IF NOT EXISTS sales")
    op.execute("CREATE SCHEMA IF NOT EXISTS statustype")

# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('contact_name', sa.Text(), nullable=False),
    sa.Column('designation', sa.Text(), nullable=True),
    sa.Column('phone_no_1', sa.Text(), nullable=False),
    sa.Column('phone_no_2', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('contact_id'),
    schema='sales'
    )
    op.create_table('leaders',
    sa.Column('leader_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_id', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('designation', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('leader_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('emp_id'),
    schema='sales'
    )
    op.create_table('activity_type_status_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_type', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='statustype'
    )
    op.create_table('daily_activity_outcome',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='statustype'
    )
    op.create_table('daily_activity_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_status', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='statustype'
    )
    op.create_table('lead_product_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='statustype'
    )
    op.create_table('leader_stage_status_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('leader_stage', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='statustype'
    )
    op.create_table('product_status_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='statustype'
    )
    op.create_table('risk_matrix_status_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risk_matrix', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='statustype'
    )
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'ERROR', name='loginstatus'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sales.leaders.emp_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_index('idx_login_history_timestamp', 'login_history', ['timestamp'], unique=False)
    op.create_index('idx_login_history_user_id', 'login_history', ['user_id'], unique=False)
    op.create_index('idx_login_history_id', 'login_history', ['id'], unique=False)
    op.create_table('auth_leader',
    sa.Column('auth_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_id', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('refresh_token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('refresh_token_expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['sales.leaders.emp_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('auth_id'),
    sa.UniqueConstraint('refresh_token'),
    sa.UniqueConstraint('refresh_token_hash'),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_auth_leader_emp_id'), 'auth_leader', ['emp_id'], unique=False, schema='sales')
    op.create_table('lead_register',
    sa.Column('lead_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lead_owner_id', sa.Integer(), nullable=True),
    sa.Column('lead_source', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('contact_name', sa.Text(), nullable=True),
    sa.Column('designation', sa.Text(), nullable=True),
    sa.Column('phone_no', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('project_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('expected_closure', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['lead_owner_id'], ['sales.leaders.leader_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('lead_id'),
    schema='sales'
    )
    op.create_table('lead_activity_register',
    sa.Column('activity_id', sa.Text(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('lead_owner_id', sa.Integer(), nullable=True),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('activity_type_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('outcome_id', sa.Integer(), nullable=True),
    sa.Column('action_status_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('lead_no', sa.Integer(), autoincrement=True, nullable=True),
    sa.ForeignKeyConstraint(['action_status_id'], ['statustype.daily_activity_status.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['activity_type_id'], ['statustype.activity_type_status_type.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['sales.lead_register.lead_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_owner_id'], ['sales.leaders.leader_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outcome_id'], ['statustype.daily_activity_outcome.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('activity_id'),
    schema='sales'
    )
    op.create_table('product_register',
    sa.Column('product_register_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('probability', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('won', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('pipeline', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('risk_matrix', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['sales.lead_register.lead_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['statustype.product_status_type.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_id'], ['statustype.leader_stage_status_type.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['statustype.lead_product_status.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('product_register_id'),
    schema='sales'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_register', schema='sales')
    op.drop_table('lead_activity_register', schema='sales')
    op.drop_table('lead_register', schema='sales')
    op.drop_table('auth_leader', schema='sales')
    op.drop_table('login_history')
    op.drop_table('risk_matrix_status_type', schema='statustype')
    op.drop_table('product_status_type', schema='statustype')
    op.drop_table('leader_stage_status_type', schema='statustype')
    op.drop_table('lead_product_status', schema='statustype')
    op.drop_table('daily_activity_status', schema='statustype')
    op.drop_table('daily_activity_outcome', schema='statustype')
    op.drop_table('activity_type_status_type', schema='statustype')
    op.drop_table('leaders', schema='sales')
    op.drop_table('contacts', schema='sales')
    # ### end Alembic commands ###
