"""Add password_reset_otp table

Revision ID: 02d8836ae476
Revises: 20260910_mail_events_resp
Create Date: 2026-09-11 15:27:24.725974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02d8836ae476'
down_revision: Union[str, None] = '20260910_mail_events_resp'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_otp',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp_code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_password_reset_otp_email'), 'password_reset_otp', ['email'], unique=False, schema='sales')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_password_reset_otp_email'), table_name='password_reset_otp', schema='sales')
    op.drop_table('password_reset_otp', schema='sales')
    # ### end Alembic commands ###

